---
apiVersion: v1
kind: ReplicationController
metadata:
  name: drywall-flowlog-stats-mock
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drywall-flowlog-stats-mock
    spec:
      containers:
      - name: drywall-flowlog-stats
        image: garland/drywall-flowlog-stats:mock
        command: ["forever","mock-server.js"]
        resources:
          limits:
            cpu: 1000m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 50Mi
        # env:
        #   - name: PASSWORD
        #     value: password
        #   - name: PORT
        #     value: "57575"
        ports:
          - containerPort: 3000
        imagePullPolicy: "Always"

      imagePullSecrets:
      - name: garlandregistry
