---

FLEET_API_BASE_PATH: v1-alpha
FLEET_API_PORT: 49153

coreos_unit_base_name: redis
EXPOSED_REDIS_PORT: 26379

service_name: redis-sentinel

#redis_data_directory: /home/core/redis-files/data

# Logging
LOG_PATH: "/opt/redis/logs"

DIRECTORIES_TO_MONITOR: "/var/redis/logs,/var/log"