---
- name: create a new user for Ubuntu nodes
  user: name={{ item.name }} shell=/bin/bash
  with_items: "{{ add_users }}"
  when: ansible_distribution == "Ubuntu"

- name: create a new user for CoreOS nodes
  user: name={{ item.name }} shell=/bin/bash password=*
  with_items: "{{ add_users }}"
  when: ansible_distribution != "Ubuntu"

- name: create sudoers.d directory
  file: path=/etc/sudoers.d owner=0 group=0 mode=0750 state=directory

- name: create sudoers
  template: src=sudoers.d.j2
    dest=/etc/sudoers.d/{{ item.name }}
    mode=0440
    owner=root
    group=root
    validate='/usr/sbin/visudo -cf %s'
  with_items: "{{ add_users }}"

- name: add authorized key
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: "{{ add_users }}"
