apiVersion: v1
data:
  # https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#http-strict-transport-security
  hsts: "false"
  hsts-include-subdomains: "false"
  force-hsts: "false"
  body-size: "2000m"
  server-name-hash-bucket-size: "100"
  # https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#nginx-status-page
  enable-vts-status: "true"
kind: ConfigMap
metadata:
  name: nginx-load-balancer-conf
