apiVersion: v1
kind: ReplicationController
metadata:
  name: aa-test-http-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aa-test-http-server
    spec:
      containers:
      - name: aa-test-http-server
        image: vungle/test-http-server:1.0
        ports:
        - containerPort: 3000
